### Save event
POST {{localhost}}:{{port}}/api/event
Content-Type: application/json

{
  "name": "test",
  "isIndoor": true,
  "date": "2027-04-21T23:59:59",
  "totalCost": 33.5,
  "imageUrl": "https://test.de"
}

> {%
    var res = response.body
    client.global.set("id", res.id)
 %}

### Get all events
GET {{localhost}}:{{port}}/api/event

### Get event by id
GET {{localhost}}:{{port}}/api/event/{{id}}

### Add participant to event
GET {{localhost}}:{{port}}/api/event/{{id}}/participant/afb3392b-33c1-4040-96ea-dd70d48e3354

### Split cost over all participants
GET {{localhost}}:{{port}}/api/event/{{id}}/split-costs